"""initial migration

Revision ID: 2a110ac33ea8
Revises: None
Create Date: 2016-04-10 14:37:58.763906

"""

# revision identifiers, used by Alembic.
revision = '2a110ac33ea8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrapecounts', sa.Column('date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrapecounts', 'date')
    ### end Alembic commands ###
